fiction = CategoryTree::Category.new(:code => 'FIC', :name => 'Fiction')
fiction.save(:validate => false)
fiction.children.new(:code => 'POETRY', :name => 'Poetry').save(:validate => false)
prose = fiction.children.new(:code => 'PROSE', :name => 'Prose')
prose.save(:validate => false)
prose.children.new(:code => 'YA', :name => 'Young Adult').save(:validate => false)
fantasy = prose.children.new(:code => 'FAN', :name => 'Fantasy')
fantasy.save(:validate => false)
fantasy.children.new(:code => 'MEDFAN', :name => 'Medieval Fantasy').save(:validate => false)

nonfiction = CategoryTree::Category.new(:code => 'NFIC', :name => 'Non Fiction')
nonfiction.save(:validate => false)
biography = nonfiction.children.new(:code => 'BIO', :name => 'Biographies')
biography.save(:validate => false)
biography.children.new(:code => 'AUTOBIO', :name => 'Autobiographies').save(:validate => false)
biography.children.new(:code => 'POLIBIO', :name => 'Politician Biographies').save(:validate => false)
